name: Bug / Issue Report
description: Form for reporting bugs and issues
body:
  - type: markdown
    attributes:
      value: |
        Create a report to help us improve Chai!
  - type: markdown
    attributes:
      value: |
        ## <ins>User Information</ins>
  - type: dropdown
    id: os
    attributes:
      label: Operating System (OS)
      description: What operating system is your phone or tablet running?
      options:
        - iOS / iPadOS
        - AndroidOS
    validations:
      required: true
  - type: input
    id: chai-ver
    attributes:
      label: Chai App Version
      description: What version of the Chai app are you using?<br>You can find this under "Profile" -> "Settings" -> "App Version".
      placeholder: x.x.xxx (Android) or xxxxxxxx.x.x (iOS)
    validations:
      required: true
  - type: dropdown
    id: login
    attributes:
      label: Login Type
      description: How are you logging into the Chai app?
      options:
        - Apple ID (iOS-only)
        - Google
        - Facebook
    validations:
      required: true
  - type: dropdown
    id: subscription
    attributes:
      label: Account Type
      description: What type of subscription do you currently have, if applicable?<br>Please select "none" if you prefer not to answer.
      options:
        - Premium
        - Ultra
        - Not applicable
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## <ins>Identification</ins>
  - type: input
    id: botid
    attributes:
      label: What is the bot's ID?
      description: This is the "https://chai.ml" URL for the bot. You can find it under "Share" -> "Copy" in any bot.<br>You can also type answers such as "not applicable" or "affects all bots" if you prefer.
      placeholder: https://chai.ml/chat/share/_bot_12345678-90ab-cdef-ghij-jlmnopqrstuv
    validations:
      required: true
  - type: input
    id: userid
    attributes:
      label: What is your user ID?
      description: You can find this under "Profile" -> "Settings" -> "User ID".<br>You can also type answers such as "not applicable" or "affects all users" if you prefer.
      placeholder: 1234567890abcdefghijklmnopqr                   
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <small>Please note that while optional, this helps devs fix issues much faster, and without it may result in the whatever bug being reported going undiscovered for longer.</small>
        
        ## <ins>Details of Issue</ins>
  - type: dropdown
    id: frequency
    attributes:
      label: Frequency of Occurrence
      description: How often does this issue happen?
      options:
        - Always
        - Frequently
        - Occasionally
        - Rarely
        - Not applicable
    validations:
      required: true
  - type: input
    id: expectation
    attributes:
      label: Expected Behavior
      description: What do you expect to happen when doing this task?
    validations:
      required: true
  - type: input
    id: actuality
    attributes:
      label: Actual Behavior
      description: What is actually happening when doing this task?
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: Do you have any additional information about this bug or issue?
    validations:
      required: false
